--SHOW THE COUNTRY WHERE COUNT OF MOVIE GRATER THAN TV SHOWS 
--THIS TYPE OF QUETION WE USE CASE WHEN 
SELECT country,COUNT(*) AS total_count 
FROM netflix_titles 
GROUP by country
HAVING 
SUM(CASE WHEN type='Movie' THEN 1 ELSE 0 END)>
SUM(CASE WHEN type='TV Show' THEN 1 ELSE 0 END );