--SHOW THE COUNTRIES WHO HAVE TV SHOW AND MOVIES BOTH 
--HERE THIS KIND OF QUE WE USE DISTINCT 
--IT ONLY COUNTS UNIQUE VALUE SO WHENEVER IT SEES BOTH VALUE IT WILL GIVE THAT CONTRY 
SELECT country 
FROM netflix_titles 
GROUP BY country 
HAVING COUNT(DISTINCT type) =2;
